### ISSUE TITLE
"num_classes" error when training customize dataset 

### ISSUE THREAD

**Issue by foolhard** [ViTAE-Transformer/ViTDet#17]
Hello, 

Thanks for your great job. 
I found an error when I train vitdet on customized dataset.  
I have already change the **num_classes=8** in model config. 
but it seems that the module.num_classes are still 80.  

Could you help me? 

Traceback (most recent call last):
  File "tools/train.py", line 189, in <module>
    main()
  File "tools/train.py", line 178, in main
    train_detector(
  File "/dfs/data/open_mmlab/mmdet_ViTDet/mmdet/apis/train.py", line 180, in train_detector
    runner.run(data_loaders, cfg.workflow)
  File "/dfs/data/miniconda/envs/mmdet_vitdet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 127, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "/dfs/data/miniconda/envs/mmdet_vitdet/lib/python3.8/site-packages/mmcv/runner/epoch_based_runner.py", line 45, in train
    self.call_hook('before_train_epoch')
  File "/dfs/data/miniconda/envs/mmdet_vitdet/lib/python3.8/site-packages/mmcv/runner/base_runner.py", line 307, in call_hook
    getattr(hook, fn_name)(self)
  File "/dfs/data/open_mmlab/mmdet_ViTDet/mmdet/datasets/utils.py", line 160, in before_train_epoch
    self._check_head(runner)
  File "/dfs/data/open_mmlab/mmdet_ViTDet/mmdet/datasets/utils.py", line 146, in _check_head
    assert module.num_classes == len(dataset.CLASSES), \
**AssertionError: The `num_classes` (80) in ViT of MMDataParallel does not matches the length of `CLASSES` 8) in CustomizedDataset**

**Comment by foolhard** [comment]
Here is the model config>



_model = dict(
    type='MaskRCNN',
    pretrained=None,
    backbone=dict(
        type='ViT',
        img_size=1024,
        embed_dim=768,
        depth=12,
        num_heads=12,
        mlp_ratio=4,
        qkv_bias=True,
        qk_scale=None,
        drop_rate=0.0,
        attn_drop_rate=0.0,
        drop_path_rate=0.1,
        use_abs_pos_emb=True),
    neck=dict(
        type='FPN',
        in_channels=[768, 768, 768, 768],
        out_channels=256,
        norm_cfg=dict(type='LN', requires_grad=True),
        use_residual=False,
        num_outs=5),
    rpn_head=dict(
        type='RPNHead',
        num_convs=2,
        norm_cfg=dict(type='LN', requires_grad=True),
        in_channels=256,
        feat_channels=256,
        anchor_generator=dict(
            type='AnchorGenerator',
            scales=[8],
            ratios=[0.5, 1.0, 2.0],
            strides=[4, 8, 16, 32, 64]),
        bbox_coder=dict(
            type='DeltaXYWHBBoxCoder',
            target_means=[0.0, 0.0, 0.0, 0.0],
            target_stds=[1.0, 1.0, 1.0, 1.0]),
        loss_cls=dict(
            type='CrossEntropyLoss', use_sigmoid=True, loss_weight=1.0),
        loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
    roi_head=dict(
        type='StandardRoIHead',
        bbox_roi_extractor=dict(
            type='SingleRoIExtractor',
            roi_layer=dict(type='RoIAlign', output_size=7, sampling_ratio=0),
            out_channels=256,
            featmap_strides=[4, 8, 16, 32]),
        bbox_head=dict(
            type='Shared4Conv1FCBBoxHead',
            conv_out_channels=256,
            norm_cfg=dict(type='LN', requires_grad=True),
            in_channels=256,
            fc_out_channels=1024,
            roi_feat_size=7,
            **num_classes=8,**
            bbox_coder=dict(
                type='DeltaXYWHBBoxCoder',
                target_means=[0.0, 0.0, 0.0, 0.0],
                target_stds=[0.1, 0.1, 0.2, 0.2]),
            reg_class_agnostic=False,
            loss_cls=dict(
                type='CrossEntropyLoss', use_sigmoid=False, loss_weight=1.0),
            loss_bbox=dict(type='L1Loss', loss_weight=1.0)),
        mask_roi_extractor=None,
        mask_head=None),
    train_cfg=dict(
        rpn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.7,
                neg_iou_thr=0.3,
                min_pos_iou=0.3,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=256,
                pos_fraction=0.5,
                neg_pos_ub=-1,
                add_gt_as_proposals=False),
            allowed_border=-1,
            pos_weight=-1,
            debug=False),
        rpn_proposal=dict(
            nms_pre=2000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            assigner=dict(
                type='MaxIoUAssigner',
                pos_iou_thr=0.5,
                neg_iou_thr=0.5,
                min_pos_iou=0.5,
                match_low_quality=True,
                ignore_iof_thr=-1),
            sampler=dict(
                type='RandomSampler',
                num=512,
                pos_fraction=0.25,
                neg_pos_ub=-1,
                add_gt_as_proposals=True),
            pos_weight=-1,
            debug=False)),
    test_cfg=dict(
        rpn=dict(
　　　nms_pre=1000,
            max_per_img=1000,
            nms=dict(type='nms', iou_threshold=0.7),
            min_bbox_size=0),
        rcnn=dict(
            score_thr=0.05,
            nms=dict(type='nms', iou_threshold=0.5),
            max_per_img=100)))_

**Comment by foolhard** [comment]
The root cause is a parameter **_num_classes_** is defined in funciton of _mmdet/models/backbones/vit.py_.
Actually **_### num_classes_** is not used in _vit.py_.

Simply removed this parameter can solve the problem. 

![无标题](https://user-images.githubusercontent.com/13057970/178402635-37df337a-22d4-4fab-9f20-6f65d90430bd.png)
