### ISSUE TITLE
  Problems in the use of pre training model

### ISSUE THREAD

**Issue by wudizuixiaosa** [ViTAE-Transformer/ViTDet#7]
Hello, first of all, thank you for your amazing results. I obtained the pre training model of Imagenet 1K in Mae released by Facebook research before, and then loaded my own coco format data set for training, but an error occurred. Have you encountered this type of problem before. In addition, I read your vitaev2 paper, which mentioned that you used Mae to train vitae. Is there any specific operation method, such as where to modify the overall Mae.
Traceback (most recent call last):
  File "tools/train.py", line 190, in <module>
    main()
  File "tools/train.py", line 186, in main
    meta=meta)
  File "/home/lzh/miniconda3/envs/det2/lib/python3.7/site-packages/mmdet-2.18.0-py3.7.egg/mmdet/apis/train.py", line 177, in train_detector
    runner.resume(cfg.resume_from)
  File "/home/lzh/miniconda3/envs/det2/lib/python3.7/site-packages/mmcv/runner/base_runner.py", line 361, in resume
    self._epoch = checkpoint['meta']['epoch']
KeyError: 'meta'

**Comment by Annbless** [comment]
The pretrained models should be loaded by specifying the `model.pretrained` options, not the `resume_from` options. Please refer to [Usage](https://github.com/ViTAE-Transformer/ViTDet#usage) for detailed commands.

**Comment by wudizuixiaosa** [comment]
> 



> The pretrained models should be loaded by specifying the `model.pretrained` options, not the `resume_from` options. Please refer to [Usage](https://github.com/ViTAE-Transformer/ViTDet#usage) for detailed commands.

Ha ha, forgive me for not reading the usage carefully. Thank you for your timely reply. I wish you a happy life.

**Comment by wudizuixiaosa** [comment]
If it's convenient, can you answer by the way? I read your vitaev2 paper, which mentioned that you train vitae with MAE. Whether there are any specific operation methods, such as where to modify the overall MAE. I am very interested in this because Mae cannot use PVT or swin due to its specific input method.

**Comment by Annbless** [comment]
Hi,

Please refer to Sec 3.3 and Sec 4.4.1 in the [ViTAEv2](https://arxiv.org/pdf/2202.10108.pdf) paper. We use MAE to train the isotropic design of ViTAE, not the hierarchical ViTAEv2 backbone. We will explore training hierarchical ViTAEv2 backbone using MIM series methods in the future.

**Comment by xmdgaoxin** [comment]
Hello, how can I solve the following error when I use my own coco dataset during training
![捕获](https://user-images.githubusercontent.com/58241242/201512808-82901ce7-5068-4c41-a179-97d4b4ca2be7.PNG)
